#!/usr/bin/env node

'use strict';

if (Number(process.version.match(/\d+/)[0]) < 5) {
    console.error('This script requires nodejs v5 or greater.');
    process.exit(1);
}

const range = require('lodash/range');
const Promise = require('bluebird');
const mkdirp = Promise.promisify(require('mkdirp'));
const badge = Promise.promisify(require('gh-badges'));
const writeFile = Promise.promisify(require('fs').writeFile);
const svg2png = require('svg2png');

const dir = `${__dirname}/../badges`;

function getColorschemeForPercentage(percentage) {
    if (percentage > 90) {
        return 'brightgreen';
    }
    if (percentage > 75) {
        return 'green';
    }
    if (percentage > 60) {
        return 'yellowgreen';
    }
    if (percentage > 40) {
        return 'yellow';
    }

    return 'red';
}

function generateBadge(percentage, style) {
    // Generate svg
    return Promise.try(() => {
        const isUnknown = typeof percentage !== 'number';
        const value = !isUnknown ? `${percentage}%` : 'unknown';
        const colorscheme = !isUnknown ? getColorschemeForPercentage(percentage) : 'lightgrey';

        console.log(`Generating ${percentage}-${style}.svg`);

        return new Promise((resolve, reject) => {
            badge({ text: ['npms score', value], colorscheme, template: style }, (svg, err) => {
                if (err) {
                    reject(err);
                } else {
                    resolve(new Buffer(svg));
                }
            });
        })
        .tap((svgBuffer) => writeFile(`${dir}/${percentage}/${percentage}-${style}.svg`, svgBuffer));
    })
    // Generate png
    .then((svgBuffer) => {
        console.log(`Generating ${percentage}-${style}.png`);

        return svg2png(svgBuffer)
        .then((pngBuffer) => writeFile(`${dir}/${percentage}/${percentage}-${style}.png`, pngBuffer));
    });
}

// ----------------------------------------------

const percentages = range(0, 101);
const styles = ['flat', 'flat-square', 'plastic'];

percentages.push('unknown');  // Render also an unknown badge

Promise.each(percentages, (percentage) => {
    return mkdirp(`${dir}/${percentage}`)
    .then(() => Promise.map(styles, (style) => generateBadge(percentage, style)));
}, { concurrency: 5 })
.then(() => console.log('Done!'))
.done();
