#!/usr/bin/env node

'use strict';

const range = require('lodash/range');
const Promise = require('bluebird');
const mkdirp = Promise.promisify(require('mkdirp'));
const badge = Promise.promisify(require('gh-badges'));
const writeFile = Promise.promisify(require('fs').writeFile);
const sharp = require('sharp');

const dir = `${__dirname}/../badges`;

function getColorschemeForPercentage(percentage) {
    if (percentage > 90) {
        return 'brightgreen';
    }
    if (percentage > 75) {
        return 'green';
    }
    if (percentage > 60) {
        return 'yellowgreen';
    }
    if (percentage > 40) {
        return 'yellow';
    }

    return 'red';
}

function generateBadge(percentage, style) {
    // Generate svg
    return Promise.try(() => {
        const file = `${percentage}/${percentage}-${style}.svg`;
        const isUnknown = typeof percentage !== 'number';
        const value = !isUnknown ? `${percentage}%` : 'unknown';
        const colorscheme = !isUnknown ? getColorschemeForPercentage(percentage) : 'lightgrey';

        return new Promise((resolve, reject) => {
            badge({ text: ['npms score', value], colorscheme, template: style }, (svg, err) => {
                if (err) {
                    reject(err);
                } else {
                    resolve(svg);
                }
            });
        })
        .tap((svg) => writeFile(`${dir}/${file}`, svg));
    })
    // Generate png
    .then((svg) => {
        const file = `${percentage}/${percentage}-${style}.png`;

        console.log(`Generating ${file}`);

        return new Promise((resolve, reject) => {
            sharp(new Buffer(svg))
            .toFile(`${dir}/${file}`, (err) => {
                if (err) {
                    reject(err);
                } else {
                    resolve();
                }
            });
        });
    });
}

// ----------------------------------------------

const percentages = range(0, 101);
const styles = ['flat', 'flat-square', 'plastic'];

percentages.push('unknown');  // Render also an unknown badge

Promise.each(percentages, (percentage) => {
    return mkdirp(`${dir}/${percentage}`)
    .then(() => Promise.each(styles, (style) => generateBadge(percentage, style)));
})
.then(() => console.log('Done!'))
.done();
